name: dotnet test

on: [push]

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'    # set this to the path to your web app project, defaults to the repository root

jobs:
  dagger:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install Dagger
        uses: dagger/dagger-for-github@v2
        with:
          install-only: true

      - name: Init Dagger
        run: dagger project init

      - name: Init Dependencies
        run: dagger project update

      - name: Do Tests
        run: dagger do test